# Generated by Django 2.0.4 on 2018-05-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
