# Generated by Django 2.0.4 on 2018-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0002_categoria_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(help_text='Nombre de la Categoria', max_length=45),
        ),
    ]
