# Generated by Django 2.0.5 on 2018-06-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupation', models.CharField(max_length=50, null=True, verbose_name='Ocupation')),
                ('tel', models.CharField(max_length=30, verbose_name='Telephone number')),
                ('telcel', models.CharField(max_length=30, null=True, verbose_name='Telephone number')),
                ('address', models.CharField(max_length=40, verbose_name='Your address')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('state', models.CharField(max_length=40, verbose_name='State')),
            ],
        ),
    ]
