# Generated by Django 2.0.5 on 2018-06-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180610_0019'),
        ('usuarios', '0003_remove_myuser_services'),
    ]

    operations = [
    ]
