# Generated by Django 2.0.5 on 2018-06-10 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_remove_service_users'),
        ('usuarios', '0005_merge_20180610_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Service'),
        ),
    ]
