# Generated by Django 2.0.5 on 2018-06-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0020_service_user'),
        ('photologue_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryextended',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='servicios.Service'),
            preserve_default=False,
        ),
    ]
