# Generated by Django 2.0.5 on 2018-06-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_custom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryextended',
            name='user',
        ),
    ]
