# Generated by Django 2.0.5 on 2018-06-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0021_auto_20180611_2151'),
        ('photologue_custom', '0002_remove_galleryextended_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryextended',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='servicios.Service'),
            preserve_default=False,
        ),
    ]
