# Generated by Django 2.0.5 on 2018-06-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_custom', '0002_galleryextended_service'),
        ('photologue_custom', '0003_galleryextended_service'),
    ]

    operations = [
    ]
