# Generated by Django 2.0.5 on 2018-05-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
