# Generated by Django 2.0.5 on 2018-06-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_service_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='users',
        ),
    ]
