# Generated by Django 2.0.4 on 2018-06-04 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0009_auto_20180603_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='users',
        ),
        migrations.AddField(
            model_name='service',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
