# Generated by Django 2.0.4 on 2018-06-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_auto_20180604_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
