# Generated by Django 2.0.5 on 2018-06-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='users',
        ),
    ]
