# Generated by Django 2.0.5 on 2018-06-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_auto_20180604_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='users',
        ),
    ]
