# Generated by Django 2.0.5 on 2018-06-11 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_service_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='photologue.Gallery'),
        ),
    ]
