# Generated by Django 2.0.5 on 2018-06-11 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_auto_20180611_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='gallery',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='photologue.Gallery'),
            preserve_default=False,
        ),
    ]
