# Generated by Django 2.0.5 on 2018-06-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0018_auto_20180611_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='gallery',
        ),
    ]
