# Generated by Django 2.0.5 on 2018-06-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0020_service_user'),
        ('servicios', '0021_auto_20180611_2151'),
    ]

    operations = [
    ]
